# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tcc_msgs/location_goal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tcc_msgs.msg

class location_goal(genpy.Message):
  _md5sum = "0bd1bb248c5558be85460e2f5009eda1"
  _type = "tcc_msgs/location_goal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """point start
point goal

================================================================================
MSG: tcc_msgs/point
int32 x
int32 y
"""
  __slots__ = ['start','goal']
  _slot_types = ['tcc_msgs/point','tcc_msgs/point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start,goal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(location_goal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.start is None:
        self.start = tcc_msgs.msg.point()
      if self.goal is None:
        self.goal = tcc_msgs.msg.point()
    else:
      self.start = tcc_msgs.msg.point()
      self.goal = tcc_msgs.msg.point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.start.x, _x.start.y, _x.goal.x, _x.goal.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.start is None:
        self.start = tcc_msgs.msg.point()
      if self.goal is None:
        self.goal = tcc_msgs.msg.point()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.start.x, _x.start.y, _x.goal.x, _x.goal.y,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.start.x, _x.start.y, _x.goal.x, _x.goal.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.start is None:
        self.start = tcc_msgs.msg.point()
      if self.goal is None:
        self.goal = tcc_msgs.msg.point()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.start.x, _x.start.y, _x.goal.x, _x.goal.y,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
