// Generated by gencpp from file trabalho_final/ChangeGoal.msg
// DO NOT EDIT!


#ifndef TRABALHO_FINAL_MESSAGE_CHANGEGOAL_H
#define TRABALHO_FINAL_MESSAGE_CHANGEGOAL_H

#include <ros/service_traits.h>


#include <trabalho_final/ChangeGoalRequest.h>
#include <trabalho_final/ChangeGoalResponse.h>


namespace trabalho_final
{

struct ChangeGoal
{

typedef ChangeGoalRequest Request;
typedef ChangeGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeGoal
} // namespace trabalho_final


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trabalho_final::ChangeGoal > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::trabalho_final::ChangeGoal&) { return value(); }
};

template<>
struct DataType< ::trabalho_final::ChangeGoal > {
  static const char* value()
  {
    return "trabalho_final/ChangeGoal";
  }

  static const char* value(const ::trabalho_final::ChangeGoal&) { return value(); }
};


// service_traits::MD5Sum< ::trabalho_final::ChangeGoalRequest> should match 
// service_traits::MD5Sum< ::trabalho_final::ChangeGoal > 
template<>
struct MD5Sum< ::trabalho_final::ChangeGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trabalho_final::ChangeGoal >::value();
  }
  static const char* value(const ::trabalho_final::ChangeGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trabalho_final::ChangeGoalRequest> should match 
// service_traits::DataType< ::trabalho_final::ChangeGoal > 
template<>
struct DataType< ::trabalho_final::ChangeGoalRequest>
{
  static const char* value()
  {
    return DataType< ::trabalho_final::ChangeGoal >::value();
  }
  static const char* value(const ::trabalho_final::ChangeGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trabalho_final::ChangeGoalResponse> should match 
// service_traits::MD5Sum< ::trabalho_final::ChangeGoal > 
template<>
struct MD5Sum< ::trabalho_final::ChangeGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trabalho_final::ChangeGoal >::value();
  }
  static const char* value(const ::trabalho_final::ChangeGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trabalho_final::ChangeGoalResponse> should match 
// service_traits::DataType< ::trabalho_final::ChangeGoal > 
template<>
struct DataType< ::trabalho_final::ChangeGoalResponse>
{
  static const char* value()
  {
    return DataType< ::trabalho_final::ChangeGoal >::value();
  }
  static const char* value(const ::trabalho_final::ChangeGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRABALHO_FINAL_MESSAGE_CHANGEGOAL_H
