// Generated by gencpp from file pwm/cmd_vel_msg.msg
// DO NOT EDIT!


#ifndef PWM_MESSAGE_CMD_VEL_MSG_H
#define PWM_MESSAGE_CMD_VEL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pwm
{
template <class ContainerAllocator>
struct cmd_vel_msg_
{
  typedef cmd_vel_msg_<ContainerAllocator> Type;

  cmd_vel_msg_()
    : pwm1(0.0)
    , pwm2(0.0)
    , pwm3(0.0)  {
    }
  cmd_vel_msg_(const ContainerAllocator& _alloc)
    : pwm1(0.0)
    , pwm2(0.0)
    , pwm3(0.0)  {
  (void)_alloc;
    }



   typedef float _pwm1_type;
  _pwm1_type pwm1;

   typedef float _pwm2_type;
  _pwm2_type pwm2;

   typedef float _pwm3_type;
  _pwm3_type pwm3;




  typedef boost::shared_ptr< ::pwm::cmd_vel_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pwm::cmd_vel_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_vel_msg_

typedef ::pwm::cmd_vel_msg_<std::allocator<void> > cmd_vel_msg;

typedef boost::shared_ptr< ::pwm::cmd_vel_msg > cmd_vel_msgPtr;
typedef boost::shared_ptr< ::pwm::cmd_vel_msg const> cmd_vel_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pwm::cmd_vel_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pwm::cmd_vel_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pwm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pwm': ['/home/tony/catkin_ws/src/tcc/pwm/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pwm::cmd_vel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pwm::cmd_vel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm::cmd_vel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm::cmd_vel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm::cmd_vel_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm::cmd_vel_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pwm::cmd_vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e03293df3d14e0aa43909bef4c94fc72";
  }

  static const char* value(const ::pwm::cmd_vel_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe03293df3d14e0aaULL;
  static const uint64_t static_value2 = 0x43909bef4c94fc72ULL;
};

template<class ContainerAllocator>
struct DataType< ::pwm::cmd_vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pwm/cmd_vel_msg";
  }

  static const char* value(const ::pwm::cmd_vel_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pwm::cmd_vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pwm1\n\
float32 pwm2\n\
float32 pwm3\n\
";
  }

  static const char* value(const ::pwm::cmd_vel_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pwm::cmd_vel_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm1);
      stream.next(m.pwm2);
      stream.next(m.pwm3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_vel_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pwm::cmd_vel_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pwm::cmd_vel_msg_<ContainerAllocator>& v)
  {
    s << indent << "pwm1: ";
    Printer<float>::stream(s, indent + "  ", v.pwm1);
    s << indent << "pwm2: ";
    Printer<float>::stream(s, indent + "  ", v.pwm2);
    s << indent << "pwm3: ";
    Printer<float>::stream(s, indent + "  ", v.pwm3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PWM_MESSAGE_CMD_VEL_MSG_H
