// Generated by gencpp from file serial_node/PIDparams.msg
// DO NOT EDIT!


#ifndef SERIAL_NODE_MESSAGE_PIDPARAMS_H
#define SERIAL_NODE_MESSAGE_PIDPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_node
{
template <class ContainerAllocator>
struct PIDparams_
{
  typedef PIDparams_<ContainerAllocator> Type;

  PIDparams_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , setpoint(0.0)
    , min(0.0)
    , max(0.0)  {
    }
  PIDparams_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , setpoint(0.0)
    , min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _ki_type;
  _ki_type ki;

   typedef float _kd_type;
  _kd_type kd;

   typedef float _setpoint_type;
  _setpoint_type setpoint;

   typedef float _min_type;
  _min_type min;

   typedef float _max_type;
  _max_type max;




  typedef boost::shared_ptr< ::serial_node::PIDparams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_node::PIDparams_<ContainerAllocator> const> ConstPtr;

}; // struct PIDparams_

typedef ::serial_node::PIDparams_<std::allocator<void> > PIDparams;

typedef boost::shared_ptr< ::serial_node::PIDparams > PIDparamsPtr;
typedef boost::shared_ptr< ::serial_node::PIDparams const> PIDparamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_node::PIDparams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_node::PIDparams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial_node': ['/home/tony/catkin_ws/src/serial_node/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::PIDparams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::PIDparams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node::PIDparams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node::PIDparams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::PIDparams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::PIDparams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_node::PIDparams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d703500b36bd081738aa374697bbd39";
  }

  static const char* value(const ::serial_node::PIDparams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d703500b36bd081ULL;
  static const uint64_t static_value2 = 0x738aa374697bbd39ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_node::PIDparams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_node/PIDparams";
  }

  static const char* value(const ::serial_node::PIDparams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_node::PIDparams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n\
float32 ki\n\
float32 kd\n\
float32 setpoint\n\
float32 min\n\
float32 max\n\
";
  }

  static const char* value(const ::serial_node::PIDparams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_node::PIDparams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.setpoint);
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDparams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_node::PIDparams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_node::PIDparams_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
    s << indent << "setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint);
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_NODE_MESSAGE_PIDPARAMS_H
