// Generated by gencpp from file serial_node/ResetAngle.msg
// DO NOT EDIT!


#ifndef SERIAL_NODE_MESSAGE_RESETANGLE_H
#define SERIAL_NODE_MESSAGE_RESETANGLE_H

#include <ros/service_traits.h>


#include <serial_node/ResetAngleRequest.h>
#include <serial_node/ResetAngleResponse.h>


namespace serial_node
{

struct ResetAngle
{

typedef ResetAngleRequest Request;
typedef ResetAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetAngle
} // namespace serial_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_node::ResetAngle > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::serial_node::ResetAngle&) { return value(); }
};

template<>
struct DataType< ::serial_node::ResetAngle > {
  static const char* value()
  {
    return "serial_node/ResetAngle";
  }

  static const char* value(const ::serial_node::ResetAngle&) { return value(); }
};


// service_traits::MD5Sum< ::serial_node::ResetAngleRequest> should match 
// service_traits::MD5Sum< ::serial_node::ResetAngle > 
template<>
struct MD5Sum< ::serial_node::ResetAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_node::ResetAngle >::value();
  }
  static const char* value(const ::serial_node::ResetAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_node::ResetAngleRequest> should match 
// service_traits::DataType< ::serial_node::ResetAngle > 
template<>
struct DataType< ::serial_node::ResetAngleRequest>
{
  static const char* value()
  {
    return DataType< ::serial_node::ResetAngle >::value();
  }
  static const char* value(const ::serial_node::ResetAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_node::ResetAngleResponse> should match 
// service_traits::MD5Sum< ::serial_node::ResetAngle > 
template<>
struct MD5Sum< ::serial_node::ResetAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_node::ResetAngle >::value();
  }
  static const char* value(const ::serial_node::ResetAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_node::ResetAngleResponse> should match 
// service_traits::DataType< ::serial_node::ResetAngle > 
template<>
struct DataType< ::serial_node::ResetAngleResponse>
{
  static const char* value()
  {
    return DataType< ::serial_node::ResetAngle >::value();
  }
  static const char* value(const ::serial_node::ResetAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_NODE_MESSAGE_RESETANGLE_H
