// Generated by gencpp from file opencv_node/SetParams.msg
// DO NOT EDIT!


#ifndef OPENCV_NODE_MESSAGE_SETPARAMS_H
#define OPENCV_NODE_MESSAGE_SETPARAMS_H

#include <ros/service_traits.h>


#include <opencv_node/SetParamsRequest.h>
#include <opencv_node/SetParamsResponse.h>


namespace opencv_node
{

struct SetParams
{

typedef SetParamsRequest Request;
typedef SetParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParams
} // namespace opencv_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opencv_node::SetParams > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::opencv_node::SetParams&) { return value(); }
};

template<>
struct DataType< ::opencv_node::SetParams > {
  static const char* value()
  {
    return "opencv_node/SetParams";
  }

  static const char* value(const ::opencv_node::SetParams&) { return value(); }
};


// service_traits::MD5Sum< ::opencv_node::SetParamsRequest> should match 
// service_traits::MD5Sum< ::opencv_node::SetParams > 
template<>
struct MD5Sum< ::opencv_node::SetParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_node::SetParams >::value();
  }
  static const char* value(const ::opencv_node::SetParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_node::SetParamsRequest> should match 
// service_traits::DataType< ::opencv_node::SetParams > 
template<>
struct DataType< ::opencv_node::SetParamsRequest>
{
  static const char* value()
  {
    return DataType< ::opencv_node::SetParams >::value();
  }
  static const char* value(const ::opencv_node::SetParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opencv_node::SetParamsResponse> should match 
// service_traits::MD5Sum< ::opencv_node::SetParams > 
template<>
struct MD5Sum< ::opencv_node::SetParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_node::SetParams >::value();
  }
  static const char* value(const ::opencv_node::SetParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_node::SetParamsResponse> should match 
// service_traits::DataType< ::opencv_node::SetParams > 
template<>
struct DataType< ::opencv_node::SetParamsResponse>
{
  static const char* value()
  {
    return DataType< ::opencv_node::SetParams >::value();
  }
  static const char* value(const ::opencv_node::SetParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENCV_NODE_MESSAGE_SETPARAMS_H
