// Generated by gencpp from file tcc_msgs/location_goal.msg
// DO NOT EDIT!


#ifndef TCC_MSGS_MESSAGE_LOCATION_GOAL_H
#define TCC_MSGS_MESSAGE_LOCATION_GOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tcc_msgs/point.h>
#include <tcc_msgs/point.h>

namespace tcc_msgs
{
template <class ContainerAllocator>
struct location_goal_
{
  typedef location_goal_<ContainerAllocator> Type;

  location_goal_()
    : start()
    , goal()  {
    }
  location_goal_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tcc_msgs::point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::tcc_msgs::point_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::tcc_msgs::location_goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tcc_msgs::location_goal_<ContainerAllocator> const> ConstPtr;

}; // struct location_goal_

typedef ::tcc_msgs::location_goal_<std::allocator<void> > location_goal;

typedef boost::shared_ptr< ::tcc_msgs::location_goal > location_goalPtr;
typedef boost::shared_ptr< ::tcc_msgs::location_goal const> location_goalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tcc_msgs::location_goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tcc_msgs::location_goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tcc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tcc_msgs': ['/home/tony/catkin_ws/src/tcc/tcc_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tcc_msgs::location_goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tcc_msgs::location_goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tcc_msgs::location_goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tcc_msgs::location_goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tcc_msgs::location_goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tcc_msgs::location_goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tcc_msgs::location_goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bd1bb248c5558be85460e2f5009eda1";
  }

  static const char* value(const ::tcc_msgs::location_goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bd1bb248c5558beULL;
  static const uint64_t static_value2 = 0x85460e2f5009eda1ULL;
};

template<class ContainerAllocator>
struct DataType< ::tcc_msgs::location_goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tcc_msgs/location_goal";
  }

  static const char* value(const ::tcc_msgs::location_goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tcc_msgs::location_goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point start\n\
point goal\n\
\n\
================================================================================\n\
MSG: tcc_msgs/point\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::tcc_msgs::location_goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tcc_msgs::location_goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct location_goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tcc_msgs::location_goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tcc_msgs::location_goal_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::tcc_msgs::point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::tcc_msgs::point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TCC_MSGS_MESSAGE_LOCATION_GOAL_H
